# Generated by Django 5.2.9 on 2026-01-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('year', models.IntegerField(db_index=True)),
                ('country_name', models.CharField(max_length=100)),
                ('iso_ref', models.CharField(db_index=True, max_length=3)),
                ('continent', models.CharField(db_index=True, max_length=50)),
                ('incidents_count', models.IntegerField()),
                ('fatalities', models.IntegerField()),
                ('threat_type', models.CharField(max_length=50)),
                ('intel_confidence', models.FloatField()),
                ('hotspot_score', models.FloatField(blank=True, null=True)),
                ('intensity_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'iso_ref'], name='analytics_c_timesta_6c6431_idx'), models.Index(fields=['continent'], name='analytics_c_contine_54bcc7_idx'), models.Index(fields=['year', 'iso_ref'], name='analytics_c_year_a1f01f_idx')],
            },
        ),
    ]
